name: Conda

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

  schedule:
    - cron: '0 * */1 * *'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: true
      matrix:
        arch: [ x64, arm, arm64 ]

        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/my-env

          - os: macos-latest
            label: osx-64
            prefix: /Users/runner/miniconda3/envs/my-env

          - os: windows-latest
            label: win-64
            prefix: C:\Miniconda3\envs\my-env

    env:
      CGID: conda-${{matrix.os}}-${{matrix.arch}}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: my-env
          use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/cache@v2
        with:
          path: |
            ${{ matrix.prefix }}

          key: ${{ matrix.label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run: |
          pip install -r requirements-test.txt
          mamba env update -f environment.yml
          #if: steps.cache.outputs.cache-hit != 'true'

      - name: Lint with flake8
        run: |
          echo "linting bypassed"
      #        conda install flake8
      #        # stop the build if there are Python syntax errors or undefined names
      #        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Cache Pytest
        id: cache-pytest
        uses: actions/cache@v3
        with:
          path: .pytest_cache
          key: conda-${{matrix.arch}}-${{ runner.os }}-${{matrix.python-version}}-${{hashFiles('test_*.py')}}.pytest_cache


      - name: Test with pytest cached
        continue-on-error: true
        run: |
          pytest

      - name: Test with pytest
        run: |
          pytest -p no:cacheprovider
